In [1]:
import numpy as np

In [18]:
import builtins
list = builtins.list


In [7]:
list=[1,2,3,4,5,6]
np_arr=np.array(list)
print(np_arr,type(np_arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [ ]:
#shape attribute returns number of element in each dimension
np_arr.shape

(6,)

In [ ]:
my_list = list(range(0, 12))
np_array=np.array(my_list)
print(np_array)
print(np_array.shape)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [22]:
np_arr

array([1, 2, 3, 4, 5, 6])

In [24]:
np_arr.size



6

In [ ]:
np_arr.reshape((2, 3))  #for 2D


array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np_arr.reshape((2,3, 1))  #for 3D


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [ ]:
np_arr.reshape((2,3, 1))  #for 3D
#npdim attribute provides the number of dimension of numpy array
np3d=np_arr.ndim
print(np3d)

1


In [34]:
np_arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into a 3D array
reshaped_arr = np_arr.reshape((2, 3, 1))
print("Reshaped array:")
print(reshaped_arr)

# Get the number of dimensions
np3d = reshaped_arr.ndim
print("Number of dimensions:", np3d)

Reshaped array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
Number of dimensions: 3


array([1, 2, 3, 4, 5, 6])

In [29]:
# Reshape into a 4D array
reshaped_arr = np_arr.reshape((1, 2, 3, 1))
print(reshaped_arr)

[[[[1]
   [2]
   [3]]

  [[4]
   [5]
   [6]]]]


In [36]:
np_arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])
np_array_2d=np_arr.reshape((3,4))
np_array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
np_array_2d[2] # access dim 1 element and that is array of index 2

array([ 9, 10, 11, 12])

In [ ]:
np_array_2d[2][1] #individual element lai access ganra yesari garxa suppose 10 element bhankeo 

np.int64(10)

In [43]:
np_array_2d[2,1]

np.int64(10)

In [48]:
np_arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])
np_array_2d=np_arr.reshape((3,4))
np_array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
np_array_2d[1:,2:]

array([[ 7,  8],
       [11, 12]])